{
 "title": "Node Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{},node)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"node_exporter\",nodename=~\"$node\"}, instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod CPU使用量",
   "type": "timeseries",
   "description": "单位(C 核)",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"\",instance=~\"$node\",namespace=~\"$namespace\"}[30s])) by (pod, namespace)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU使用率",
   "type": "timeseries",
   "description": "分母为Limit值",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"\",instance=~\"$node\",namespace=~\"$namespace\"}[1m])) by (pod, namespace) / (sum(container_spec_cpu_quota{image!=\"\",instance=~\"$node\"}/container_spec_cpu_period{image!=\"\",instance=~\"$node\",namespace=~\"$namespace\"}) by (pod, namespace)) * 100",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pod 内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",instance=~\"$node\",namespace=~\"$namespace\"}) by (pod, namespace)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pod 内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",instance=~\"$node\",namespace=~\"$namespace\"}) by (pod, namespace)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$instance\"} - node_boot_time_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "启动时间",
   "type": "stat",
   "description": "在此时启动, 启动后不再变化",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_boot_time_seconds{instance=~\"$instance\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\"}[30s])) by (instance) / sum (irate(node_cpu_seconds_total{instance=~\"$instance\"}[30s])) by (instance) * 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{instance=~\"$instance\"}) by (instance) - sum(node_memory_MemAvailable_bytes{instance=~\"$instance\"}) by (instance)) / sum (node_memory_MemTotal_bytes{instance=~\"$instance\"}) by (instance) * 100",
     "legendFormat": "内存"
    },
    {
     "expr": "avg by (instance) (rate(node_disk_io_time_seconds_total{instance=~\"$instance\"}[30s])) * 100",
     "legendFormat": "IO"
    }
   ]
  },
  {
   "title": "Load负载",
   "type": "stat",
   "description": "load1",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU核数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\"}[30s]))",
     "legendFormat": "Used"
    },
    {
     "expr": "count by (instance) (node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "内存",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "磁盘",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$instance\"}) by (instance) - sum(node_filesystem_free_bytes{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Load负载",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (irate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\"}[1m])) by (instance) / sum (irate(node_cpu_seconds_total{instance=~\"$instance\"}[1m])) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{instance=~\"$instance\"}) by (instance) - sum(node_memory_MemAvailable_bytes{instance=~\"$instance\"}) by (instance)) / sum (node_memory_MemTotal_bytes{instance=~\"$instance\"}) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "磁盘读写速度",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$instance\"}[30s])",
     "legendFormat": "<-{{instance}}-{{device}}"
    },
    {
     "expr": "-irate(node_disk_read_bytes_total{instance=~\"$instance\"}[30s])",
     "legendFormat": "->{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "网络接口流量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instance\"}[30s])",
     "legendFormat": "<-{{instance}}-{{device}}"
    },
    {
     "expr": "-irate(node_network_receive_bytes_total{instance=~\"$instance\"}[30s])",
     "legendFormat": "->{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-available"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-free"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-cache"
    },
    {
     "expr": "node_memory_Active_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-active"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-swap"
    }
   ]
  }
 ]
}